# Generated by Django 2.0.5 on 2018-06-03 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocorrencias', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='endereco',
            name='numero',
            field=models.DecimalField(decimal_places=1, max_digits=12),
        ),
    ]
