# Generated by Django 2.0.5 on 2018-06-06 14:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ocorrencias', '0003_auto_20180603_1233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ocorrencia',
            name='endereco',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_endereco', to='ocorrencias.Endereco'),
        ),
        migrations.AlterField(
            model_name='ocorrencia',
            name='solicitante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_solicitante', to='ocorrencias.Solicitante'),
        ),
        migrations.AlterField(
            model_name='ocorrencia',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='from_tipo', to='ocorrencias.TipoOcorrencia'),
        ),
    ]
