# Generated by Django 2.0.5 on 2018-06-07 17:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ocorrencias', '0004_auto_20180606_1131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ocorrencia',
            name='endereco',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ocorrencias.Endereco'),
        ),
        migrations.AlterField(
            model_name='ocorrencia',
            name='solicitante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ocorrencias.Solicitante'),
        ),
        migrations.AlterField(
            model_name='ocorrencia',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ocorrencias.TipoOcorrencia'),
        ),
    ]
